import type { AppProps } from "next/app";
import { Inter, Press_Start_2P } from "next/font/google";
import Head from "next/head";

import "@/common/styles/globals.css";
import { AuthProvider } from "@/common/context";
import Header from "@/common/components/Header";
import { Container, Main } from "@/common/templates";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

const pressStart2P = Press_Start_2P({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Next.js Autentication</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <style jsx global>
        {`
          :root {
            --font-inter: ${inter.style.fontFamily};
            --font-pressStart2P: ${pressStart2P.style.fontFamily};
          }
        `}
      </style>
      <Container>
        <AuthProvider>
          <Header />

          <Main>
            <Component {...pageProps} />
          </Main>
        </AuthProvider>
      </Container>
    </>
  );
}
