import Head from "next/head";

import { useAuthContext } from "@/common/context";
import Can from "@/common/components/Can";

export default function Home() {
  const authContext = useAuthContext();

  return (
    <>
      <Head>
        <title>App NextAuth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2>User: {authContext?.user?.email}</h2>
        
        <Can permissions={['metrics.list']}>
          <strong>Metricas</strong>
        </Can>
      </main>
    </>
  );
}
