import Head from "next/head";

import { useAuthContext } from "@/common/context";

export default function Home() {
  const authContext = useAuthContext();

  return (
    <>
      <Head>
        <title>App NextAuth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2>Home Page</h2>
        <h4>User: {authContext?.user?.email}</h4>
      </main>
    </>
  );
}
