import Head from "next/head";
import * as React from "react";
import { useAuthContext } from "@/common/context";

const SignIn = () => {
  const authContext = useAuthContext();

  const [email, setEmail] = React.useState("");
  const [password, setPassword] = React.useState("");

  const handleEmailChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setEmail(event.target.value);
  };

  const handlePasswordChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setPassword(event.target.value);
  };

  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const data = new FormData(event.currentTarget);

    const email = data.get("email")! as string;
    const password = data.get("password")! as string;

    await authContext?.signIn({ email, password });
  };

  return (
    <>
      <Head>
        <title>Next.js Autentication</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen bg-gradient-to-r from-green-300">
        <div className="w-full h-full flex justify-center items-center">
          <form onSubmit={handleSubmit}>
            <div className="w-auto grid grid-cols-1 gap-4 justify-center items-center text-center">
              <h2 className="text-lg font-normal font-pressStart2P">
                Next.js <br />
                Autentication
              </h2>

              <input
                className="h-10 px-2 text-black text-base bg-green-50 placeholder:text-sm placeholder:text-green-900 rounded-md outline-none"
                type="email"
                id="email"
                name="email"
                placeholder="E-mail"
                value={email}
                onChange={handleEmailChange}
                required
              />

              <input
                className="h-10 px-2 text-black text-base bg-green-50 placeholder:text-sm placeholder:text-green-900 rounded-md outline-none"
                id="password"
                type="password"
                name="password"
                placeholder="Password"
                value={password}
                onChange={handlePasswordChange}
                required
              />
              <button
                type="submit"
                className="p-2 text-white font-bold bg-green-600 hover:bg-green-800 rounded-md transition-colors duration-500"
              >
                Sign in
              </button>
            </div>
          </form>
        </div>
      </main>
    </>
  );
};

export default SignIn;
